const SALARY_CERTIFICATE = "Salary Certificate"
const SALARY_TRANSFER_LETTER = "Salary Transfer Letter"
const EXPERIENCE_LETTER = "Experience Letter"

const SALARY_CERTIFICATE_SHORT = "SC"
const SALARY_TRANSFER_LETTER_SHORT = "STL"
const EXPERIENCE_LETTER_SHORT = "EL"

const CERTIFICATES_OBJ = {
  [SALARY_CERTIFICATE_SHORT]: SALARY_CERTIFICATE,
  [SALARY_TRANSFER_LETTER_SHORT]: SALARY_TRANSFER_LETTER,
  [EXPERIENCE_LETTER_SHORT]: EXPERIENCE_LETTER,
}

const CERTIFICATES_SHORT_OBJ = {
  [SALARY_CERTIFICATE]: SALARY_CERTIFICATE_SHORT,
  [SALARY_TRANSFER_LETTER]: SALARY_TRANSFER_LETTER_SHORT,
  [EXPERIENCE_LETTER]: EXPERIENCE_LETTER_SHORT,
}

module.exports = {
  CERTIFICATES_OBJ,
  SALARY_CERTIFICATE_SHORT,
  SALARY_TRANSFER_LETTER_SHORT,
  EXPERIENCE_LETTER_SHORT,
  SALARY_CERTIFICATE,
  SALARY_TRANSFER_LETTER,
  EXPERIENCE_LETTER,
  CERTIFICATES_SHORT_OBJ
}